server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://rm-wz9v8xc42t1go7ptc0o.mysql.rds.aliyuncs.com:3306/lifecapsule
    username: root
    password: 112233ccddEE
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/application-lifecapsule.log